### POST patient at /patients endpoint
POST http://localhost.localstack.cloud:4004/api/patients
Authorization: Bearer {{token}}}
Content-Type: application/json

{
    "name": "John Kafka",
    "email": "kafka.test11@gmail.com",
    "address": "address124",
    "dateOfBirth": "1997-10-10",
    "registeredDate": "2025-04-03"
}

###